PREFIX example: <http://example.com/> 

SELECT * WHERE{ 
SERVICE <http://127.0.0.1:8890/sparql> {?s a example:class_0.5} 
OPTIONAL {  
	SERVICE <http://127.0.0.1:8890/sparql> { ?s  example:property_card1_prop0_member0 ?o1 }} 
OPTIONAL { 
  	SERVICE <http://127.0.0.1:8891/sparql> { ?s example:property_empty_prop1_member1 ?o2 }} 
} 